// Generated by scripts/build-annual-gap-matrix.mjs; no local teaching inference.
import type { AnnualPlanningScope } from './annualReadiness';
export const annualReadinessRegistry = [
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Langue française",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-0"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "English language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-1"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Langues et cultures nationales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-2"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Initiation aux mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-fr-primary-sil-1",
      "annual-math-v1-fr-primary-sil-2",
      "annual-math-v1-fr-primary-sil-3",
      "annual-math-v1-fr-primary-sil-4",
      "annual-math-v1-fr-primary-sil-5",
      "annual-math-v1-fr-primary-sil-6",
      "annual-math-v1-fr-primary-sil-7",
      "annual-math-v1-fr-primary-sil-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Initiation aux sciences et à la technologie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-4"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Technologies de l’information et de la communication",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-5"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Sciences humaines et sociales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-6"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-7"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-sil",
    "subjectName": "Développement personnel",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-sil-subject-9"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Langue française",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-0"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "English language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-1"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Langues et cultures nationales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-2"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Initiation aux mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-fr-primary-cp-1",
      "annual-math-v1-fr-primary-cp-2",
      "annual-math-v1-fr-primary-cp-3",
      "annual-math-v1-fr-primary-cp-4",
      "annual-math-v1-fr-primary-cp-5",
      "annual-math-v1-fr-primary-cp-6",
      "annual-math-v1-fr-primary-cp-7",
      "annual-math-v1-fr-primary-cp-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Initiation aux sciences et à la technologie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-4"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Technologies de l’information et de la communication",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-5"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Sciences humaines et sociales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-6"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-7"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cp",
    "subjectName": "Développement personnel",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cp-subject-9"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Français et littérature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-0"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "English language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-1"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Langues et cultures nationales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-2"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-fr-primary-ce1-1",
      "annual-math-v1-fr-primary-ce1-2",
      "annual-math-v1-fr-primary-ce1-3",
      "annual-math-v1-fr-primary-ce1-4",
      "annual-math-v1-fr-primary-ce1-5",
      "annual-math-v1-fr-primary-ce1-6",
      "annual-math-v1-fr-primary-ce1-7",
      "annual-math-v1-fr-primary-ce1-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Sciences et technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-4"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Technologies de l’information et de la communication",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-5"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Sciences humaines et sociales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-6"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-7"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "COMPLETE",
    "structuredContent": [
      "annual-verified-fr-primary-ce1-eps-1",
      "annual-verified-fr-primary-ce1-eps-2",
      "annual-verified-fr-primary-ce1-eps-3",
      "annual-verified-fr-primary-ce1-eps-4",
      "annual-verified-fr-primary-ce1-eps-5",
      "annual-verified-fr-primary-ce1-eps-6",
      "annual-verified-fr-primary-ce1-eps-7",
      "annual-verified-fr-primary-ce1-eps-8",
      "annual-verified-fr-primary-ce1-eps-9",
      "annual-verified-fr-primary-ce1-eps-10",
      "annual-verified-fr-primary-ce1-eps-11"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Développement personnel",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce1-subject-9"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Français et littérature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-0"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "English language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-1"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Langues et cultures nationales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-2"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-fr-primary-ce2-1",
      "annual-math-v1-fr-primary-ce2-2",
      "annual-math-v1-fr-primary-ce2-3",
      "annual-math-v1-fr-primary-ce2-4",
      "annual-math-v1-fr-primary-ce2-5",
      "annual-math-v1-fr-primary-ce2-6",
      "annual-math-v1-fr-primary-ce2-7",
      "annual-math-v1-fr-primary-ce2-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Sciences et technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-4"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Technologies de l’information et de la communication",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-5"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Sciences humaines et sociales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-6"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-7"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "COMPLETE",
    "structuredContent": [
      "annual-verified-fr-primary-ce2-eps-1",
      "annual-verified-fr-primary-ce2-eps-2",
      "annual-verified-fr-primary-ce2-eps-3",
      "annual-verified-fr-primary-ce2-eps-4",
      "annual-verified-fr-primary-ce2-eps-5",
      "annual-verified-fr-primary-ce2-eps-6",
      "annual-verified-fr-primary-ce2-eps-7",
      "annual-verified-fr-primary-ce2-eps-8",
      "annual-verified-fr-primary-ce2-eps-9",
      "annual-verified-fr-primary-ce2-eps-10",
      "annual-verified-fr-primary-ce2-eps-11"
    ]
  },
  {
    "catalogLevelId": "fr-primary-ce2",
    "subjectName": "Développement personnel",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-ce2-subject-9"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Français et littérature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-0"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "English language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-1"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Langues et cultures nationales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-2"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-fr-primary-cm1-1",
      "annual-math-v1-fr-primary-cm1-2",
      "annual-math-v1-fr-primary-cm1-3",
      "annual-math-v1-fr-primary-cm1-4",
      "annual-math-v1-fr-primary-cm1-5",
      "annual-math-v1-fr-primary-cm1-7",
      "annual-math-v1-fr-primary-cm1-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Sciences et technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-4"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Technologies de l’information et de la communication",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-5"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Sciences humaines et sociales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-6"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-7"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm1",
    "subjectName": "Développement personnel",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm1-subject-9"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Français et littérature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-0"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "English language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-1"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Langues et cultures nationales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-2"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-fr-primary-cm2-1",
      "annual-math-v1-fr-primary-cm2-2",
      "annual-math-v1-fr-primary-cm2-3",
      "annual-math-v1-fr-primary-cm2-4",
      "annual-math-v1-fr-primary-cm2-5",
      "annual-math-v1-fr-primary-cm2-7",
      "annual-math-v1-fr-primary-cm2-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Sciences et technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-4"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Technologies de l’information et de la communication",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-5"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Sciences humaines et sociales",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-6"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-7"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-8"
    ]
  },
  {
    "catalogLevelId": "fr-primary-cm2",
    "subjectName": "Développement personnel",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-primary-cm2-subject-9"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "English Language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-0"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-en-primary-1-1",
      "annual-math-v1-en-primary-1-2",
      "annual-math-v1-en-primary-1-3",
      "annual-math-v1-en-primary-1-4",
      "annual-math-v1-en-primary-1-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Science and Technology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-2"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-3"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Social Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-4"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Vocational Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Arts",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-6"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Physical Education and Sports",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-7"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "National Languages and Cultures",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-8"
    ]
  },
  {
    "catalogLevelId": "en-primary-1",
    "subjectName": "Information and Communication Technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-1-subject-9"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "English Language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-0"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-en-primary-2-1",
      "annual-math-v1-en-primary-2-2",
      "annual-math-v1-en-primary-2-3",
      "annual-math-v1-en-primary-2-4",
      "annual-math-v1-en-primary-2-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Science and Technology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-2"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-3"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Social Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-4"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Vocational Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Arts",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-6"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Physical Education and Sports",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-7"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "National Languages and Cultures",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-8"
    ]
  },
  {
    "catalogLevelId": "en-primary-2",
    "subjectName": "Information and Communication Technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-2-subject-9"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "English Language and Literature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-0"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-en-primary-3-1",
      "annual-math-v1-en-primary-3-2",
      "annual-math-v1-en-primary-3-3",
      "annual-math-v1-en-primary-3-4",
      "annual-math-v1-en-primary-3-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Science and Technology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-2"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-3"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Social Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-4"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Vocational Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Arts",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-6"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Physical Education and Sports",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-7"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "National Languages and Cultures",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-8"
    ]
  },
  {
    "catalogLevelId": "en-primary-3",
    "subjectName": "Information and Communication Technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-3-subject-9"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "English Language and Literature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-0"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-en-primary-4-1",
      "annual-math-v1-en-primary-4-2",
      "annual-math-v1-en-primary-4-3",
      "annual-math-v1-en-primary-4-4",
      "annual-math-v1-en-primary-4-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Science and Technology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-2"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-3"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Social Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-4"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Vocational Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Arts",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-6"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Physical Education and Sports",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-7"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "National Languages and Cultures",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-8"
    ]
  },
  {
    "catalogLevelId": "en-primary-4",
    "subjectName": "Information and Communication Technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-4-subject-9"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "English Language and Literature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-0"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-en-primary-5-1",
      "annual-math-v1-en-primary-5-2",
      "annual-math-v1-en-primary-5-3",
      "annual-math-v1-en-primary-5-4",
      "annual-math-v1-en-primary-5-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Science and Technology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-2"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-3"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Social Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-4"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Vocational Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Arts",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-6"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Physical Education and Sports",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-7"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "National Languages and Cultures",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-8"
    ]
  },
  {
    "catalogLevelId": "en-primary-5",
    "subjectName": "Information and Communication Technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-5-subject-9"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "English Language and Literature",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-0"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-math-v1-en-primary-6-1",
      "annual-math-v1-en-primary-6-2",
      "annual-math-v1-en-primary-6-3",
      "annual-math-v1-en-primary-6-4",
      "annual-math-v1-en-primary-6-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Science and Technology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-2"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-3"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Social Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-4"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Vocational Studies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-5"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Arts",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-6"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Physical Education and Sports",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-7"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "National Languages and Cultures",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-8"
    ]
  },
  {
    "catalogLevelId": "en-primary-6",
    "subjectName": "Information and Communication Technologies",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-primary-6-subject-9"
    ]
  },
  {
    "catalogLevelId": "fr-preschool-pre",
    "subjectName": "Langues et communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-pre-d1",
      "annual-plan-v1-fr-preschool-pre-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-pre",
    "subjectName": "Éveil scientifique et technologique",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-pre-d2",
      "annual-plan-v1-fr-preschool-pre-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-pre",
    "subjectName": "Vie courante",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-pre-d3",
      "annual-plan-v1-fr-preschool-pre-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-pre",
    "subjectName": "Création artistique et activités manuelles",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-pre-d4",
      "annual-plan-v1-fr-preschool-pre-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-pre",
    "subjectName": "Motricité générale",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-pre-d5",
      "annual-plan-v1-fr-preschool-pre-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ps",
    "subjectName": "Langues et communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ps-d1",
      "annual-plan-v1-fr-preschool-ps-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ps",
    "subjectName": "Éveil scientifique et technologique",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ps-d2",
      "annual-plan-v1-fr-preschool-ps-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ps",
    "subjectName": "Vie courante",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ps-d3",
      "annual-plan-v1-fr-preschool-ps-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ps",
    "subjectName": "Création artistique et activités manuelles",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ps-d4",
      "annual-plan-v1-fr-preschool-ps-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ps",
    "subjectName": "Motricité générale",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ps-d5",
      "annual-plan-v1-fr-preschool-ps-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ms",
    "subjectName": "Langues et communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ms-d1",
      "annual-plan-v1-fr-preschool-ms-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ms",
    "subjectName": "Éveil scientifique et technologique",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ms-d2",
      "annual-plan-v1-fr-preschool-ms-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ms",
    "subjectName": "Vie courante",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ms-d3",
      "annual-plan-v1-fr-preschool-ms-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ms",
    "subjectName": "Création artistique et activités manuelles",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ms-d4",
      "annual-plan-v1-fr-preschool-ms-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-ms",
    "subjectName": "Motricité générale",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-ms-d5",
      "annual-plan-v1-fr-preschool-ms-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-gs",
    "subjectName": "Langues et communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-gs-d1",
      "annual-plan-v1-fr-preschool-gs-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-gs",
    "subjectName": "Éveil scientifique et technologique",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-gs-d2",
      "annual-plan-v1-fr-preschool-gs-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-gs",
    "subjectName": "Vie courante",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-gs-d3",
      "annual-plan-v1-fr-preschool-gs-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-gs",
    "subjectName": "Création artistique et activités manuelles",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-gs-d4",
      "annual-plan-v1-fr-preschool-gs-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-preschool-gs",
    "subjectName": "Motricité générale",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-fr-preschool-gs-d5",
      "annual-plan-v1-fr-preschool-gs-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-pre",
    "subjectName": "Literacy and Communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-pre-d1",
      "annual-plan-v1-en-nursery-pre-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-pre",
    "subjectName": "Science and Technological Skills Development",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-pre-d2",
      "annual-plan-v1-en-nursery-pre-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-pre",
    "subjectName": "Practical Life Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-pre-d3",
      "annual-plan-v1-en-nursery-pre-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-pre",
    "subjectName": "Arts and Crafts",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-pre-d4",
      "annual-plan-v1-en-nursery-pre-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-pre",
    "subjectName": "Motor Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-pre-d5",
      "annual-plan-v1-en-nursery-pre-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-1",
    "subjectName": "Literacy and Communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-1-d1",
      "annual-plan-v1-en-nursery-1-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-1",
    "subjectName": "Science and Technological Skills Development",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-1-d2",
      "annual-plan-v1-en-nursery-1-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-1",
    "subjectName": "Practical Life Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-1-d3",
      "annual-plan-v1-en-nursery-1-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-1",
    "subjectName": "Arts and Crafts",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-1-d4",
      "annual-plan-v1-en-nursery-1-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-1",
    "subjectName": "Motor Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-1-d5",
      "annual-plan-v1-en-nursery-1-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-2",
    "subjectName": "Literacy and Communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-2-d1",
      "annual-plan-v1-en-nursery-2-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-2",
    "subjectName": "Science and Technological Skills Development",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-2-d2",
      "annual-plan-v1-en-nursery-2-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-2",
    "subjectName": "Practical Life Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-2-d3",
      "annual-plan-v1-en-nursery-2-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-2",
    "subjectName": "Arts and Crafts",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-2-d4",
      "annual-plan-v1-en-nursery-2-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-2",
    "subjectName": "Motor Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-2-d5",
      "annual-plan-v1-en-nursery-2-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-3",
    "subjectName": "Literacy and Communication",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-3-d1",
      "annual-plan-v1-en-nursery-3-d1"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-3",
    "subjectName": "Science and Technological Skills Development",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-3-d2",
      "annual-plan-v1-en-nursery-3-d2"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-3",
    "subjectName": "Practical Life Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-3-d3",
      "annual-plan-v1-en-nursery-3-d3"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-3",
    "subjectName": "Arts and Crafts",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-3-d4",
      "annual-plan-v1-en-nursery-3-d4"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "en-nursery-3",
    "subjectName": "Motor Skills",
    "coverageStatus": "ITALO_VALIDATED",
    "structuredContent": [
      "italo-early-v1-en-nursery-3-d5",
      "annual-plan-v1-en-nursery-3-d5"
    ],
    "validatedFor": {
      "kind": "ITALO_PEDAGOGICAL_CHOICE",
      "version": "local-annual-2026-09-20-v1",
      "schoolId": "school-italo-official",
      "academicYearId": "ay_school-italo-official_2026-2027_er0p",
      "authority": "Mission explicite de validation pédagogique déléguée",
      "reversible": true,
      "scope": "LOCAL_ANNUAL_CONTENT_NOT_CLASS_ADOPTION"
    }
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-35-fr-secondary-6e-module-1",
      "minesec-35-fr-secondary-6e-module-2",
      "minesec-35-fr-secondary-6e-module-3",
      "minesec-35-fr-secondary-6e-module-4"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Informatique",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Sciences",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-6e-37-opening"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Éducation à la citoyenneté",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-6e-38-1",
      "annual-gap-v1-fr-secondary-6e-38-2",
      "annual-gap-v1-fr-secondary-6e-38-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Géographie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-6e-39-1",
      "annual-gap-v1-fr-secondary-6e-39-2",
      "annual-gap-v1-fr-secondary-6e-39-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Histoire",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-6e-40-1",
      "annual-gap-v1-fr-secondary-6e-40-2",
      "annual-gap-v1-fr-secondary-6e-40-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-35-fr-secondary-5e-module-1",
      "minesec-35-fr-secondary-5e-module-2",
      "minesec-35-fr-secondary-5e-module-3",
      "minesec-35-fr-secondary-5e-module-4"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Informatique",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Sciences",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-5e-37-opening"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Éducation à la citoyenneté",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-5e-38-1",
      "annual-gap-v1-fr-secondary-5e-38-2",
      "annual-gap-v1-fr-secondary-5e-38-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Géographie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-5e-39-1",
      "annual-gap-v1-fr-secondary-5e-39-2"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Histoire",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-5e-40-1",
      "annual-gap-v1-fr-secondary-5e-40-2",
      "annual-gap-v1-fr-secondary-5e-40-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-44-1",
      "annual-gap-v1-fr-secondary-4e-44-2",
      "annual-gap-v1-fr-secondary-4e-44-3",
      "annual-gap-v1-fr-secondary-4e-44-4",
      "annual-gap-v1-fr-secondary-4e-44-5"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-52-fr-secondary-4e-module-1",
      "minesec-52-fr-secondary-4e-module-2",
      "minesec-52-fr-secondary-4e-module-3",
      "minesec-52-fr-secondary-4e-module-4"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Éducation à la citoyenneté",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-53-1",
      "annual-gap-v1-fr-secondary-4e-53-2"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Géographie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-54-1",
      "annual-gap-v1-fr-secondary-4e-54-2",
      "annual-gap-v1-fr-secondary-4e-54-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Histoire",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-55-1",
      "annual-gap-v1-fr-secondary-4e-55-2",
      "annual-gap-v1-fr-secondary-4e-55-3",
      "annual-gap-v1-fr-secondary-4e-55-4"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Éducation artistique et culturelle",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-43-1",
      "annual-gap-v1-fr-secondary-4e-43-2",
      "annual-gap-v1-fr-secondary-4e-43-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Anglais",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-42-1",
      "annual-gap-v1-fr-secondary-4e-42-2",
      "annual-gap-v1-fr-secondary-4e-42-3",
      "annual-gap-v1-fr-secondary-4e-42-4",
      "annual-gap-v1-fr-secondary-4e-42-5"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Allemand",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-51-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Arabe",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-46-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Espagnol",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-48-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Chinois",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-47-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Latin-Grec",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-4e-49-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Français",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-44-1",
      "annual-gap-v1-fr-secondary-3e-44-2",
      "annual-gap-v1-fr-secondary-3e-44-3",
      "annual-gap-v1-fr-secondary-3e-44-4",
      "annual-gap-v1-fr-secondary-3e-44-5"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Mathématiques",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-52-fr-secondary-3e-module-1",
      "minesec-52-fr-secondary-3e-module-2",
      "minesec-52-fr-secondary-3e-module-3",
      "minesec-52-fr-secondary-3e-module-4"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Éducation à la citoyenneté",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-53-1",
      "annual-gap-v1-fr-secondary-3e-53-2",
      "annual-gap-v1-fr-secondary-3e-53-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Géographie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-54-1",
      "annual-gap-v1-fr-secondary-3e-54-2",
      "annual-gap-v1-fr-secondary-3e-54-3",
      "annual-gap-v1-fr-secondary-3e-54-4",
      "annual-gap-v1-fr-secondary-3e-54-5"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Histoire",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-55-1",
      "annual-gap-v1-fr-secondary-3e-55-2",
      "annual-gap-v1-fr-secondary-3e-55-3",
      "annual-gap-v1-fr-secondary-3e-55-4"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Éducation artistique et culturelle",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-43-1",
      "annual-gap-v1-fr-secondary-3e-43-2",
      "annual-gap-v1-fr-secondary-3e-43-3"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Anglais",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-42-1",
      "annual-gap-v1-fr-secondary-3e-42-2",
      "annual-gap-v1-fr-secondary-3e-42-3",
      "annual-gap-v1-fr-secondary-3e-42-4",
      "annual-gap-v1-fr-secondary-3e-42-5"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Allemand",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-51-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Arabe",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-46-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Espagnol",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-48-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Chinois",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-47-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Latin-Grec",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-3e-49-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-2nde",
    "subjectName": "Anglais",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-2nde",
    "subjectName": "Informatique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-2nde-79-conditional",
      "annual-gap-v1-fr-secondary-2nde-80-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-2nde",
    "subjectName": "SVTEEHB",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-2nde-146-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-2nde",
    "subjectName": "Éducation artistique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-2nde-144-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-2nde",
    "subjectName": "Chimie",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-2nde",
    "subjectName": "Physique",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-terminale",
    "subjectName": "Histoire",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-terminale-200-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-terminale",
    "subjectName": "Géographie",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-terminale-202-conditional"
    ]
  },
  {
    "catalogLevelId": "fr-secondary-terminale",
    "subjectName": "Informatique",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-fr-secondary-terminale-195-conditional",
      "annual-gap-v1-fr-secondary-terminale-196-conditional"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Computer Science",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form1-2-1",
      "annual-gap-v1-en-secondary-form1-2-2"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-8-en-secondary-form1-module-1",
      "minesec-8-en-secondary-form1-module-2",
      "minesec-8-en-secondary-form1-module-3",
      "minesec-8-en-secondary-form1-module-4"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form1-5-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Physics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form1-10-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Computer Science",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form2-2-1",
      "annual-gap-v1-en-secondary-form2-2-2"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-8-en-secondary-form2-module-1",
      "minesec-8-en-secondary-form2-module-2",
      "minesec-8-en-secondary-form2-module-3",
      "minesec-8-en-secondary-form2-module-4",
      "minesec-8-en-secondary-form2-module-5"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form2-5-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Physics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form2-10-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-62-en-secondary-form3-module-1",
      "minesec-62-en-secondary-form3-module-2",
      "minesec-62-en-secondary-form3-module-3",
      "minesec-62-en-secondary-form3-module-4",
      "minesec-62-en-secondary-form3-module-5"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Computer Science",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-59-1",
      "annual-gap-v1-en-secondary-form3-59-2"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "French",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-57-1",
      "annual-gap-v1-en-secondary-form3-57-2",
      "annual-gap-v1-en-secondary-form3-57-3",
      "annual-gap-v1-en-secondary-form3-57-4",
      "annual-gap-v1-en-secondary-form3-57-5"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Physics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-63-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Chemistry",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-69-1",
      "annual-gap-v1-en-secondary-form3-69-2",
      "annual-gap-v1-en-secondary-form3-69-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Citizenship Education",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-72-1",
      "annual-gap-v1-en-secondary-form3-72-2",
      "annual-gap-v1-en-secondary-form3-72-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Economics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-73-1",
      "annual-gap-v1-en-secondary-form3-73-2",
      "annual-gap-v1-en-secondary-form3-73-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Geography",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-74-1",
      "annual-gap-v1-en-secondary-form3-74-2",
      "annual-gap-v1-en-secondary-form3-74-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "History",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form3-75-1",
      "annual-gap-v1-en-secondary-form3-75-2"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-62-en-secondary-form4-module-1",
      "minesec-62-en-secondary-form4-module-2",
      "minesec-62-en-secondary-form4-module-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Computer Science",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-59-1",
      "annual-gap-v1-en-secondary-form4-59-2"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "French",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-57-1",
      "annual-gap-v1-en-secondary-form4-57-2",
      "annual-gap-v1-en-secondary-form4-57-3",
      "annual-gap-v1-en-secondary-form4-57-4",
      "annual-gap-v1-en-secondary-form4-57-5"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Physics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-63-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Chemistry",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-69-1",
      "annual-gap-v1-en-secondary-form4-69-2",
      "annual-gap-v1-en-secondary-form4-69-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Citizenship Education",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-72-1",
      "annual-gap-v1-en-secondary-form4-72-2",
      "annual-gap-v1-en-secondary-form4-72-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Economics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-73-1",
      "annual-gap-v1-en-secondary-form4-73-2",
      "annual-gap-v1-en-secondary-form4-73-3",
      "annual-gap-v1-en-secondary-form4-73-4"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Geography",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-74-1",
      "annual-gap-v1-en-secondary-form4-74-2"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "History",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-75-1",
      "annual-gap-v1-en-secondary-form4-75-2",
      "annual-gap-v1-en-secondary-form4-75-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Human Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-71-1",
      "annual-gap-v1-en-secondary-form4-71-2",
      "annual-gap-v1-en-secondary-form4-71-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Geology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form4-70-1",
      "annual-gap-v1-en-secondary-form4-70-2",
      "annual-gap-v1-en-secondary-form4-70-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Mathematics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "minesec-62-en-secondary-form5-module-1",
      "minesec-62-en-secondary-form5-module-2",
      "minesec-62-en-secondary-form5-module-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Computer Science",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-59-1",
      "annual-gap-v1-en-secondary-form5-59-2",
      "annual-gap-v1-en-secondary-form5-59-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "French",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-57-1",
      "annual-gap-v1-en-secondary-form5-57-2",
      "annual-gap-v1-en-secondary-form5-57-3",
      "annual-gap-v1-en-secondary-form5-57-4",
      "annual-gap-v1-en-secondary-form5-57-5"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Physics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-63-opening"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Chemistry",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-69-1",
      "annual-gap-v1-en-secondary-form5-69-2",
      "annual-gap-v1-en-secondary-form5-69-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Citizenship Education",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-72-1",
      "annual-gap-v1-en-secondary-form5-72-2",
      "annual-gap-v1-en-secondary-form5-72-3",
      "annual-gap-v1-en-secondary-form5-72-4"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Economics",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-73-1",
      "annual-gap-v1-en-secondary-form5-73-2",
      "annual-gap-v1-en-secondary-form5-73-3",
      "annual-gap-v1-en-secondary-form5-73-4",
      "annual-gap-v1-en-secondary-form5-73-5"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Geography",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-74-1"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "History",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-75-1",
      "annual-gap-v1-en-secondary-form5-75-2",
      "annual-gap-v1-en-secondary-form5-75-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Human Biology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-71-1",
      "annual-gap-v1-en-secondary-form5-71-2",
      "annual-gap-v1-en-secondary-form5-71-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Geology",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-form5-70-1",
      "annual-gap-v1-en-secondary-form5-70-2",
      "annual-gap-v1-en-secondary-form5-70-3"
    ]
  },
  {
    "catalogLevelId": "en-secondary-lower-sixth",
    "subjectName": "English Language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-lower-sixth-289-shared"
    ]
  },
  {
    "catalogLevelId": "en-secondary-lower-sixth",
    "subjectName": "Literature in English",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-lower-sixth-290-shared"
    ]
  },
  {
    "catalogLevelId": "en-secondary-lower-sixth",
    "subjectName": "Computer Science",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-lower-sixth",
    "subjectName": "Information and Communication Technology",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-upper-sixth",
    "subjectName": "English Language",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-upper-sixth-289-shared"
    ]
  },
  {
    "catalogLevelId": "en-secondary-upper-sixth",
    "subjectName": "Literature in English",
    "coverageStatus": "PARTIAL_BLOCKING",
    "structuredContent": [
      "annual-gap-v1-en-secondary-upper-sixth-290-shared"
    ]
  },
  {
    "catalogLevelId": "en-secondary-upper-sixth",
    "subjectName": "Computer Science",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-upper-sixth",
    "subjectName": "Information and Communication Technology",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Français",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Anglais",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-6e",
    "subjectName": "Travail manuel",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Français",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Anglais",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-5e",
    "subjectName": "Travail manuel",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "PCT",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "SVT",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Informatique",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-4e",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "PCT",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "SVT",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Informatique",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-secondary-3e",
    "subjectName": "Éducation physique et sportive",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Chemistry",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "English Language",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "French",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Geography",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "History",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form1",
    "subjectName": "Citizenship",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Chemistry",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "English Language",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "French",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Geography",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "History",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form2",
    "subjectName": "Citizenship",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "English Language",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form3",
    "subjectName": "Literature in English",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "English Language",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form4",
    "subjectName": "Literature in English",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "English Language",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "en-secondary-form5",
    "subjectName": "Literature in English",
    "coverageStatus": "PENDING_SOURCE",
    "structuredContent": []
  },
  {
    "catalogLevelId": "fr-primary-ce1",
    "subjectName": "Éducation à l’environnement et au développement durable",
    "coverageStatus": "COMPLETE",
    "structuredContent": [
      "annual-verified-fr-primary-ce1-environment-1",
      "annual-verified-fr-primary-ce1-environment-2",
      "annual-verified-fr-primary-ce1-environment-3",
      "annual-verified-fr-primary-ce1-environment-4",
      "annual-verified-fr-primary-ce1-environment-5"
    ]
  }
] as AnnualPlanningScope[];
