import { createHash } from 'node:crypto';

// Original fixtures generated by scripts/generate-pedagogy-synthetic-documents.py,
// visually inspected before pinning. A school id or uploaded checksum is not proof.
// Changing a single byte (including metadata) requires an explicit code review.
const approved = new Map([
  ['7b0a3fdb45eacbe1e36362aee32a457378c0f65d2d85215b8ebeea8eadb2508c', 'application/pdf'],
  ['807b54f89e73ed5dccb72a7a72a28a76420bf491aab8ba70ab095ca152860189', 'application/pdf'],
  ['55db3494f87c86ab132238ffd37f2053fe6481adee3cfdb3c3f71658118991ed', 'application/pdf'],
  ['52a877ee387134da7e01f44cf2325f2825cb53aec1119cbcbf0aff81abfab8df', 'image/png'],
  ['78ab71dccf2359760379381f3c0b4711c65915de7be11fd5bcb5eb0a4a1ec582', 'image/png'],
]);
export function assertApprovedSyntheticDocument(bytes: Buffer, mimeType: string) {
  const checksum = createHash('sha256').update(bytes).digest('hex');
  if (approved.get(checksum) !== mimeType) throw new Error('AI_DOCUMENT_NOT_IN_APPROVED_SYNTHETIC_SET');
  return checksum;
}
