// Generated documentary metadata; no adoption or current-edition claim.
export const subjectMappingSources = [
  {
    "documentId": "minedub-fr-primary-1",
    "pdfPages": [
      5,
      6
    ],
    "kind": "subjects",
    "names": [
      "Langue française",
      "English language",
      "Langues et cultures nationales",
      "Initiation aux mathématiques",
      "Initiation aux sciences et à la technologie",
      "Technologies de l’information et de la communication",
      "Sciences humaines et sociales",
      "Éducation artistique",
      "Éducation physique et sportive",
      "Développement personnel"
    ],
    "title": "Curriculum primaire francophone — niveau 1 (SIL / CP)",
    "sourceVersion": "38f57980080bbfddb5fd5d4ca83b553ced3ed36ef9447eb333b9deea76b9fe81",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/5872/01-programme-niveau-01-2019.pdf",
    "edition": "2018",
    "section": "francophone",
    "units": [
      {
        "id": "primary-fr-sil-sharing",
        "documentId": "minedub-fr-primary-1",
        "sourcePdfPage": 71,
        "sourcePrintedPage": 72,
        "sourceLocator": "Unité 8 communications, nombres et calculs, colonne SIL",
        "level": "SIL",
        "subject": "Mathématiques",
        "domain": "Nombres et calculs",
        "officialUnit": "Unité 8 : communications",
        "officialLesson": null,
        "objectiveParaphrase": "Relier un partage équitable en deux ou quatre parts à une représentation fractionnaire.",
        "competencyParaphrase": "Représenter une fraction à partir du partage d’un objet ou d’une collection.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-sil",
        "officialSubject": "Initiation aux mathématiques"
      },
      {
        "id": "primary-fr-sharing",
        "documentId": "minedub-fr-primary-1",
        "sourcePdfPage": 71,
        "sourcePrintedPage": 72,
        "sourceLocator": "Nombres et calculs, unité 8 communications, colonne CP",
        "level": "CP",
        "subject": "Mathématiques",
        "domain": "Nombres et calculs",
        "officialUnit": "Unité 8 : communications",
        "officialLesson": null,
        "objectiveParaphrase": "Représenter et écrire des fractions par partage en trois ou cinq parts égales.",
        "competencyParaphrase": "Utiliser le partage équitable pour représenter une fraction.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-cp",
        "officialSubject": "Initiation aux mathématiques"
      },
      {
        "id": "primary-fr-sil-body",
        "documentId": "minedub-fr-primary-1",
        "sourcePdfPage": 82,
        "sourcePrintedPage": 83,
        "sourceLocator": "Tableau 20, unité 1 la maison, corps humain, colonne SIL",
        "level": "SIL",
        "subject": "Initiation aux sciences et à la technologie",
        "domain": "Sciences de la vie",
        "officialUnit": "Unité 1 : la maison",
        "officialLesson": null,
        "objectiveParaphrase": "Reconnaître les grandes parties du corps et les gestes de propreté corporelle.",
        "competencyParaphrase": "Observer le corps et prendre soin de soi.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-sil",
        "officialSubject": "Initiation aux sciences et à la technologie"
      },
      {
        "id": "primary-fr-cp-body",
        "documentId": "minedub-fr-primary-1",
        "sourcePdfPage": 82,
        "sourcePrintedPage": 83,
        "sourceLocator": "Tableau 20, unité 1 la maison, corps humain, colonne CP",
        "level": "CP",
        "subject": "Initiation aux sciences et à la technologie",
        "domain": "Sciences de la vie",
        "officialUnit": "Unité 1 : la maison",
        "officialLesson": null,
        "objectiveParaphrase": "Décrire les grandes parties du corps et mettre en pratique la propreté corporelle.",
        "competencyParaphrase": "Décrire le vivant et adopter des gestes de soin de soi.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-cp",
        "officialSubject": "Initiation aux sciences et à la technologie"
      }
    ]
  },
  {
    "documentId": "minedub-fr-primary-2",
    "pdfPages": [
      5,
      6
    ],
    "kind": "subjects",
    "names": [
      "Français et littérature",
      "English language",
      "Langues et cultures nationales",
      "Mathématiques",
      "Sciences et technologies",
      "Technologies de l’information et de la communication",
      "Sciences humaines et sociales",
      "Éducation artistique",
      "Éducation physique et sportive",
      "Développement personnel"
    ],
    "title": "Curriculum primaire francophone — niveau 2 (CE1 / CE2)",
    "sourceVersion": "6dc059638d59463d55f12d6c9488bf04fa1ae9c00e1d51891f80702108dce6a2",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/5868/02-programme-niveau-02-2019.pdf",
    "edition": "2018",
    "section": "francophone",
    "units": [
      {
        "id": "primary-fr-ce1-fractions",
        "documentId": "minedub-fr-primary-2",
        "sourcePdfPage": 79,
        "sourcePrintedPage": 80,
        "sourceLocator": "Unité 6 santé, nombres et calculs, colonne CE1",
        "level": "CE1",
        "subject": "Mathématiques",
        "domain": "Nombres et calculs",
        "officialUnit": "Unité 6 : santé",
        "officialLesson": null,
        "objectiveParaphrase": "Reconnaître les éléments qui composent une fraction simple.",
        "competencyParaphrase": "Mobiliser les nombres et le calcul dans une situation quotidienne.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-ce1",
        "officialSubject": "Mathématiques"
      },
      {
        "id": "primary-fr-ce2-fractions",
        "documentId": "minedub-fr-primary-2",
        "sourcePdfPage": 79,
        "sourcePrintedPage": 80,
        "sourceLocator": "Unité 6 santé, nombres et calculs, colonne CE2",
        "level": "CE2",
        "subject": "Mathématiques",
        "domain": "Nombres et calculs",
        "officialUnit": "Unité 6 : santé",
        "officialLesson": null,
        "objectiveParaphrase": "Passer de la lecture d’une fraction simple à son écriture.",
        "competencyParaphrase": "Employer une notation fractionnaire dans un problème de la vie courante.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-ce2",
        "officialSubject": "Mathématiques"
      },
      {
        "id": "primary-fr-ce1-skeleton",
        "documentId": "minedub-fr-primary-2",
        "sourcePdfPage": 95,
        "sourcePrintedPage": 96,
        "sourceLocator": "Tableau 23, unité 1 la maison, squelette humain, colonne CE1",
        "level": "CE1",
        "subject": "Sciences et technologies",
        "domain": "Sciences de la vie",
        "officialUnit": "Unité 1 : la maison",
        "officialLesson": null,
        "objectiveParaphrase": "Distinguer les catégories d’os et expliquer comment le squelette soutient le corps.",
        "competencyParaphrase": "Relier la connaissance du squelette à des postures adaptées.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-ce1",
        "officialSubject": "Sciences et technologies"
      },
      {
        "id": "primary-fr-ce2-skeleton",
        "documentId": "minedub-fr-primary-2",
        "sourcePdfPage": 95,
        "sourcePrintedPage": 96,
        "sourceLocator": "Tableau 23, unité 1 la maison, squelette humain, colonne CE2",
        "level": "CE2",
        "subject": "Sciences et technologies",
        "domain": "Sciences de la vie",
        "officialUnit": "Unité 1 : la maison",
        "officialLesson": null,
        "objectiveParaphrase": "Situer les catégories d’os dans le corps et représenter un os long.",
        "competencyParaphrase": "Relier l’organisation du squelette à sa protection et aux postures.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-ce2",
        "officialSubject": "Sciences et technologies"
      }
    ]
  },
  {
    "documentId": "minedub-fr-primary-3",
    "pdfPages": [
      5,
      6
    ],
    "kind": "subjects",
    "names": [
      "Français et littérature",
      "English language",
      "Langues et cultures nationales",
      "Mathématiques",
      "Sciences et technologies",
      "Technologies de l’information et de la communication",
      "Sciences humaines et sociales",
      "Éducation artistique",
      "Éducation physique et sportive",
      "Développement personnel"
    ],
    "title": "Curriculum primaire francophone — niveau 3 (CM1 / CM2)",
    "sourceVersion": "916bffbda61442b628c42bb8fc74703e145b6f250a51d2b06b74549ae9dcc468",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/5866/03-programme-niveau-03-2019.pdf",
    "edition": "2018",
    "section": "francophone",
    "units": [
      {
        "id": "primary-fr-cm1-fractions",
        "documentId": "minedub-fr-primary-3",
        "sourcePdfPage": 74,
        "sourcePrintedPage": 75,
        "sourceLocator": "Unité 4 métiers, nombres et calculs, colonne CM1",
        "level": "CM1",
        "subject": "Mathématiques",
        "domain": "Nombres et calculs",
        "officialUnit": "Unité 4 : métiers",
        "officialLesson": null,
        "objectiveParaphrase": "Nommer et écrire une fraction puis la situer entre deux entiers consécutifs.",
        "competencyParaphrase": "Raisonner avec des fractions pour résoudre une situation numérique.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-cm1",
        "officialSubject": "Mathématiques"
      },
      {
        "id": "primary-fr-cm2-fractions",
        "documentId": "minedub-fr-primary-3",
        "sourcePdfPage": 74,
        "sourcePrintedPage": 75,
        "sourceLocator": "Unité 4 métiers, nombres et calculs, colonne CM2",
        "level": "CM2",
        "subject": "Mathématiques",
        "domain": "Nombres et calculs",
        "officialUnit": "Unité 4 : métiers",
        "officialLesson": null,
        "objectiveParaphrase": "Relier les écritures décimale et fractionnaire, et comparer une fraction à l’unité.",
        "competencyParaphrase": "Décomposer une fraction en un entier et une partie inférieure à un.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-cm2",
        "officialSubject": "Mathématiques"
      },
      {
        "id": "primary-fr-cm1-food",
        "documentId": "minedub-fr-primary-3",
        "sourcePdfPage": 93,
        "sourcePrintedPage": 94,
        "sourceLocator": "Tableau 24, unité 1 la nature, alimentation, colonne CM1",
        "level": "CM1",
        "subject": "Sciences et technologies",
        "domain": "Sciences de la vie",
        "officialUnit": "Unité 1 : la nature",
        "officialLesson": null,
        "objectiveParaphrase": "Classer les aliments selon leur rôle et expliquer pourquoi les besoins alimentaires varient.",
        "competencyParaphrase": "Relier alimentation, besoins humains et hygiène.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-cm1",
        "officialSubject": "Sciences et technologies"
      },
      {
        "id": "primary-fr-cm2-food",
        "documentId": "minedub-fr-primary-3",
        "sourcePdfPage": 93,
        "sourcePrintedPage": 94,
        "sourceLocator": "Tableau 24, unité 1 la nature, alimentation, colonne CM2",
        "level": "CM2",
        "subject": "Sciences et technologies",
        "domain": "Sciences de la vie",
        "officialUnit": "Unité 1 : la nature",
        "officialLesson": null,
        "objectiveParaphrase": "Composer une ration en tenant compte des besoins variables de la personne.",
        "competencyParaphrase": "Mobiliser les connaissances alimentaires et les règles d’hygiène.",
        "recommendedHours": null,
        "language": "fr",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "fr-primary-cm2",
        "officialSubject": "Sciences et technologies"
      }
    ]
  },
  {
    "documentId": "minedub-en-primary-1",
    "pdfPages": [
      6,
      7
    ],
    "kind": "subjects",
    "names": [
      "English Language",
      "Mathematics",
      "Science and Technology",
      "Français",
      "Social Studies",
      "Vocational Studies",
      "Arts",
      "Physical Education and Sports",
      "National Languages and Cultures",
      "Information and Communication Technologies"
    ],
    "title": "English primary curriculum — level one (Class 1 / 2)",
    "sourceVersion": "38a7c7eddea5ede2bc05bf071716e7067fd9fb987cad2d43fd33a9e294baf957",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/5853/01-program-level-one-2019.pdf",
    "edition": "2018",
    "section": "anglophone",
    "units": [
      {
        "id": "primary-en-class2-sets",
        "documentId": "minedub-en-primary-1",
        "sourcePdfPage": 48,
        "sourcePrintedPage": 48,
        "sourceLocator": "Table 21 Mathematics, Sets and Logic, Class 2 column",
        "level": "Class 2",
        "subject": "Mathematics",
        "domain": "Sets and Logic",
        "officialUnit": null,
        "officialLesson": null,
        "objectiveParaphrase": "Sort objects using three or more attributes and depict their sets with Venn diagrams.",
        "competencyParaphrase": "Use set representations to organise objects by shared properties.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-2",
        "officialSubject": "Mathematics"
      },
      {
        "id": "primary-en-sharing",
        "documentId": "minedub-en-primary-1",
        "sourcePdfPage": 48,
        "sourcePrintedPage": 48,
        "sourceLocator": "Table 21 Mathematics, Numbers and Operations, Class 1 column",
        "level": "Class 1",
        "subject": "Mathematics",
        "domain": "Numbers and Operations",
        "officialUnit": null,
        "officialLesson": null,
        "objectiveParaphrase": "Share items fairly in the context of numbers and fractions.",
        "competencyParaphrase": "Associate quantities with numbers and use sharing in practical situations.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-1",
        "officialSubject": "Mathematics"
      },
      {
        "id": "primary-en-class1-body",
        "documentId": "minedub-en-primary-1",
        "sourcePdfPage": 51,
        "sourcePrintedPage": 51,
        "sourceLocator": "Table 22, Health Education, Human body, Class 1 column",
        "level": "Class 1",
        "subject": "Science and Technology",
        "domain": "Health Education",
        "officialUnit": "Human body",
        "officialLesson": null,
        "objectiveParaphrase": "Recognise different body parts and practise everyday cleanliness.",
        "competencyParaphrase": "Connect knowledge of the body with personal care.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-1",
        "officialSubject": "Science and Technology"
      },
      {
        "id": "primary-en-class2-body",
        "documentId": "minedub-en-primary-1",
        "sourcePdfPage": 51,
        "sourcePrintedPage": 51,
        "sourceLocator": "Table 22, Health Education, Human body, Class 2 column",
        "level": "Class 2",
        "subject": "Science and Technology",
        "domain": "Health Education",
        "officialUnit": "Human body",
        "officialLesson": null,
        "objectiveParaphrase": "Connect body parts to what they do and choose appropriate items for cleaning them.",
        "competencyParaphrase": "Use knowledge of body functions in daily personal care.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-2",
        "officialSubject": "Science and Technology"
      }
    ]
  },
  {
    "documentId": "minedub-en-primary-2",
    "pdfPages": [
      5,
      6
    ],
    "kind": "subjects",
    "names": [
      "English Language and Literature",
      "Mathematics",
      "Science and Technology",
      "Français",
      "Social Studies",
      "Vocational Studies",
      "Arts",
      "Physical Education and Sports",
      "National Languages and Cultures",
      "Information and Communication Technologies"
    ],
    "title": "English primary curriculum — level two (Class 3 / 4)",
    "sourceVersion": "1921b9d044f23849c1532f403021e0a8d23a46123d4b225b8b083b827e3fdd1c",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/5850/02-program-level-two-2019.pdf",
    "edition": "2018",
    "section": "anglophone",
    "units": [
      {
        "id": "primary-en-class3-sets",
        "documentId": "minedub-en-primary-2",
        "sourcePdfPage": 49,
        "sourcePrintedPage": 50,
        "sourceLocator": "Table 21 Mathematics, Sets and Logic, Class 3 column",
        "level": "Class 3",
        "subject": "Mathematics",
        "domain": "Sets and Logic",
        "officialUnit": null,
        "officialLesson": null,
        "objectiveParaphrase": "Explain universal sets and subsets, and distinguish finite from infinite sets.",
        "competencyParaphrase": "Compare collections through their elements and set notation.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-3",
        "officialSubject": "Mathematics"
      },
      {
        "id": "primary-en-class4-fractions",
        "documentId": "minedub-en-primary-2",
        "sourcePdfPage": 49,
        "sourcePrintedPage": 50,
        "sourceLocator": "Table 21 Mathematics, Numbers and Operations, Class 4 column",
        "level": "Class 4",
        "subject": "Mathematics",
        "domain": "Numbers and Operations",
        "officialUnit": null,
        "officialLesson": null,
        "objectiveParaphrase": "Add or subtract fractions with unlike denominators and multiply proper fractions.",
        "competencyParaphrase": "Apply fraction operations and equitable sharing in numerical problems.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-4",
        "officialSubject": "Mathematics"
      },
      {
        "id": "primary-en-class3-bones",
        "documentId": "minedub-en-primary-2",
        "sourcePdfPage": 52,
        "sourcePrintedPage": 53,
        "sourceLocator": "Table 22, Health Education, The body, Class 3 column",
        "level": "Class 3",
        "subject": "Science and Technology",
        "domain": "Health Education",
        "officialUnit": "The body",
        "officialLesson": null,
        "objectiveParaphrase": "Distinguish types of bones and value a clean appearance.",
        "competencyParaphrase": "Relate knowledge of the skeleton to personal care.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-3",
        "officialSubject": "Science and Technology"
      },
      {
        "id": "primary-en-class4-bones",
        "documentId": "minedub-en-primary-2",
        "sourcePdfPage": 52,
        "sourcePrintedPage": 53,
        "sourceLocator": "Table 22, Health Education, The body, Class 4 column",
        "level": "Class 4",
        "subject": "Science and Technology",
        "domain": "Health Education",
        "officialUnit": "The body",
        "officialLesson": null,
        "objectiveParaphrase": "Explain the functions of body parts and ways of keeping bones strong.",
        "competencyParaphrase": "Apply knowledge of the body to healthy everyday practices.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-4",
        "officialSubject": "Science and Technology"
      }
    ]
  },
  {
    "documentId": "minedub-en-primary-3",
    "pdfPages": [
      5,
      6
    ],
    "kind": "subjects",
    "names": [
      "English Language and Literature",
      "Mathematics",
      "Science and Technology",
      "Français",
      "Social Studies",
      "Vocational Studies",
      "Arts",
      "Physical Education and Sports",
      "National Languages and Cultures",
      "Information and Communication Technologies"
    ],
    "title": "English primary curriculum — level three (Class 5 / 6)",
    "sourceVersion": "3d9828312e9e4832cfdf3beb5f79bd0b2fc0bd1a2722c2f0eb5853c6946994bc",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/5849/03-program-level-three-2019.pdf",
    "edition": "2018",
    "section": "anglophone",
    "units": [
      {
        "id": "primary-en-class5-proportion",
        "documentId": "minedub-en-primary-3",
        "sourcePdfPage": 50,
        "sourcePrintedPage": 51,
        "sourceLocator": "Table 21 Mathematics, Numbers and Operations, Class 5 column",
        "level": "Class 5",
        "subject": "Mathematics",
        "domain": "Numbers and Operations",
        "officialUnit": null,
        "officialLesson": null,
        "objectiveParaphrase": "Work out simple interest and solve direct or inverse proportion problems.",
        "competencyParaphrase": "Select arithmetic operations for practical proportional situations.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-5",
        "officialSubject": "Mathematics"
      },
      {
        "id": "primary-en-class6-fractions",
        "documentId": "minedub-en-primary-3",
        "sourcePdfPage": 50,
        "sourcePrintedPage": 51,
        "sourceLocator": "Table 21 Mathematics, Numbers and Operations, Class 6 column",
        "level": "Class 6",
        "subject": "Mathematics",
        "domain": "Numbers and Operations",
        "officialUnit": null,
        "officialLesson": null,
        "objectiveParaphrase": "Solve practical numerical problems involving common and decimal fractions.",
        "competencyParaphrase": "Use mathematical operations in everyday situations while considering fair distribution.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-6",
        "officialSubject": "Mathematics"
      },
      {
        "id": "primary-en-class5-systems",
        "documentId": "minedub-en-primary-3",
        "sourcePdfPage": 53,
        "sourcePrintedPage": 54,
        "sourceLocator": "Table 22, Health Education, Human body, Class 5 column",
        "level": "Class 5",
        "subject": "Science and Technology",
        "domain": "Health Education",
        "officialUnit": "Human body",
        "officialLesson": null,
        "objectiveParaphrase": "Explain how body systems operate and represent them with labelled drawings.",
        "competencyParaphrase": "Use representations to explain the organisation of the human body.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-5",
        "officialSubject": "Science and Technology"
      },
      {
        "id": "primary-en-class6-systems",
        "documentId": "minedub-en-primary-3",
        "sourcePdfPage": 53,
        "sourcePrintedPage": 54,
        "sourceLocator": "Table 22, Health Education, Human body, Class 6 column",
        "level": "Class 6",
        "subject": "Science and Technology",
        "domain": "Health Education",
        "officialUnit": "Human body",
        "officialLesson": null,
        "objectiveParaphrase": "Describe the skeleton and explain its importance while practising habits that support healthy body systems.",
        "competencyParaphrase": "Connect body structure with everyday health practices.",
        "recommendedHours": null,
        "language": "en",
        "status": "PEDAGOGICAL_APPROVAL_REQUIRED",
        "catalogLevelId": "en-primary-6",
        "officialSubject": "Science and Technology"
      }
    ]
  },
  {
    "documentId": "minedub-fr-nursery",
    "pdfPages": [
      5,
      6
    ],
    "kind": "domains",
    "names": [
      "Langues et communication",
      "Éveil scientifique et technologique",
      "Vie courante",
      "Création artistique et activités manuelles",
      "Motricité générale"
    ],
    "title": "Curriculum maternel francophone",
    "sourceVersion": "4a7ab7a042860343b31a20ef2d4d70a0f2a5be3ddb865cc70a192cde863e7cab",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/6165/programme-maternel-2019.pdf",
    "edition": "2018",
    "section": "francophone",
    "units": []
  },
  {
    "documentId": "minedub-en-nursery",
    "pdfPages": [
      5,
      6
    ],
    "kind": "domains",
    "names": [
      "Literacy and Communication",
      "Science and Technological Skills Development",
      "Practical Life Skills",
      "Arts and Crafts",
      "Motor Skills"
    ],
    "title": "English nursery curriculum",
    "sourceVersion": "e7c44dd2f7db60e95205aace826a3eb662fccf2ef91926bcd7e96056a8b51756",
    "sourceUrl": "https://www.minedub.cm/download/350/archives/6161/program-nursery-2019.pdf",
    "edition": "2018",
    "section": "anglophone",
    "units": []
  }
];
