import {describe,it,expect} from 'vitest';
import {annualCoverageScopes,annualGapUnits,summarizeAnnualCoverage} from '../../src/features/pedagogy/resources/annualCoverage';
import {earlyYearsAnnualPlans} from '../../src/features/pedagogy/resources/earlyYearsAnnualPlans';
import {finalGapReview} from '../../src/features/pedagogy/resources/finalGapReview';
import register from '../../src/features/pedagogy/resources/finalGapReviews.json';
import type {DelegatedDecision} from '../../src/features/pedagogy/components/DelegatedValidationPanel';
describe('annual documentary closure safeguards',()=>{
 it('keeps unknown teaching separate from exact documentary counts',()=>{const s=summarizeAnnualCoverage(annualCoverageScopes);expect(s).toMatchObject({expectedDocumentaryScopes:290,COMPLETE:3,ITALO_VALIDATED:40,PARTIAL_BLOCKING:201,PENDING_SOURCE:46,NOT_APPLICABLE:0,mandatoryLocalDenominatorEstablished:false});expect(new Set(annualCoverageScopes.map(s=>s.id)).size).toBe(290);});
 it('does not turn summaries or indexes into complete annual lessons',()=>{expect(annualGapUnits.length).toBe(286);expect(new Set(annualGapUnits.map(s=>s.id)).size).toBe(286);for(const u of annualGapUnits){expect(u.period).toBeNull();expect(u.officialLesson).toBeNull();expect(u.coverage).toBe('PARTIAL');expect(u.sourceVersion).toMatch(/^[a-f0-9]{64}$/);expect(u.sourcePages.every(n=>Number.isInteger(n)&&n>0)).toBe(true);}for(const s of annualCoverageScopes){for(const id of s.structuredContent.filter(id=>id.startsWith('annual-gap-')))expect(annualGapUnits.some(u=>u.id===id&&u.subjectName===s.subjectName&&u.catalogLevelId===s.catalogLevelId)).toBe(true);}});
 it('does not approve blocked source documents by adding content',()=>{const blocked=new Set(['minesec-31','minesec-64','minesec-15','minesec-16','minesec-147','minesec-148','minesec-76']);expect(annualGapUnits.some(u=>blocked.has(u.sourceDocumentId))).toBe(false);});
 it('retains 40 original preschool activities with local, non-calendar progression',()=>{expect(earlyYearsAnnualPlans).toHaveLength(40);expect(new Set(earlyYearsAnnualPlans.map(p=>p.activityId)).size).toBe(40);for(const p of earlyYearsAnnualPlans){expect(p.officialLevelEquivalent).toBeNull();expect(p.calendarPeriod).toBeNull();expect(p.decision).toBe('ITALO_PEDAGOGICAL_CHOICE');}});
 it('keeps English Language and Literature as separate conditional scopes',()=>{for(const level of ['en-secondary-lower-sixth','en-secondary-upper-sixth']){const rows=annualCoverageScopes.filter(s=>s.catalogLevelId===level);expect(rows.some(s=>s.subjectName==='English Language')).toBe(true);expect(rows.some(s=>s.subjectName==='Literature in English')).toBe(true);expect(rows.every(s=>s.applicability==='DOCUMENTARY_ONLY_LOCAL_TEACHING_NOT_ESTABLISHED')).toBe(true);}});
 it('only overlays the reviewed tenant, year and immutable source versions',()=>{const r=register.records[0];const decision={...r,officialSubject:r.subject} as unknown as DelegatedDecision;expect(finalGapReview(decision)).toBeDefined();for(const key of ['schoolId','academicYearId','sourceVersion','mappingVersion','id'])expect(finalGapReview({...decision,[key]:'different'})).toBeUndefined();});
 it('preserves all 20 genuine owner decisions and precisely classifies 63 independent reserves',()=>{expect(register.records.filter(r=>r.status==='TRUE_OWNER_DECISION_REQUIRED')).toHaveLength(20);expect(register.records.filter(r=>r.status==='OFFICIAL_PARTIAL')).toHaveLength(63);expect(new Set(register.records.filter(r=>r.status==='TRUE_OWNER_DECISION_REQUIRED').map(r=>r.catalogLevelId)).size).toBe(6);});
});
