import type { StructuredReviewExcerpt } from './minedubVerified';

/** Short, source-column-specific paraphrases. No invented duration or annual
 * progression. These remain partial documentary extracts for human review. */
export const additionalVerifiedUnits: StructuredReviewExcerpt[] = [
  { id: 'primary-fr-sil-body', documentId: 'minedub-fr-primary-1', sourcePdfPage: 82, sourcePrintedPage: 83, sourceLocator: 'Tableau 20, unité 1 la maison, corps humain, colonne SIL', level: 'SIL', subject: 'Initiation aux sciences et à la technologie', domain: 'Sciences de la vie', officialUnit: 'Unité 1 : la maison', officialLesson: 'Le corps humain', objectiveParaphrase: 'Reconnaître les grandes parties du corps et les gestes de propreté corporelle.', competencyParaphrase: 'Observer le corps et prendre soin de soi.', recommendedHours: null, language: 'fr', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-fr-cp-body', documentId: 'minedub-fr-primary-1', sourcePdfPage: 82, sourcePrintedPage: 83, sourceLocator: 'Tableau 20, unité 1 la maison, corps humain, colonne CP', level: 'CP', subject: 'Initiation aux sciences et à la technologie', domain: 'Sciences de la vie', officialUnit: 'Unité 1 : la maison', officialLesson: 'Le corps humain', objectiveParaphrase: 'Décrire les grandes parties du corps et mettre en pratique la propreté corporelle.', competencyParaphrase: 'Décrire le vivant et adopter des gestes de soin de soi.', recommendedHours: null, language: 'fr', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-fr-ce1-skeleton', documentId: 'minedub-fr-primary-2', sourcePdfPage: 95, sourcePrintedPage: 96, sourceLocator: 'Tableau 23, unité 1 la maison, squelette humain, colonne CE1', level: 'CE1', subject: 'Sciences et technologies', domain: 'Sciences de la vie', officialUnit: 'Unité 1 : la maison', officialLesson: 'Le squelette humain', objectiveParaphrase: 'Distinguer les catégories d’os et expliquer comment le squelette soutient le corps.', competencyParaphrase: 'Relier la connaissance du squelette à des postures adaptées.', recommendedHours: null, language: 'fr', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-fr-ce2-skeleton', documentId: 'minedub-fr-primary-2', sourcePdfPage: 95, sourcePrintedPage: 96, sourceLocator: 'Tableau 23, unité 1 la maison, squelette humain, colonne CE2', level: 'CE2', subject: 'Sciences et technologies', domain: 'Sciences de la vie', officialUnit: 'Unité 1 : la maison', officialLesson: 'Le squelette humain', objectiveParaphrase: 'Situer les catégories d’os dans le corps et représenter un os long.', competencyParaphrase: 'Relier l’organisation du squelette à sa protection et aux postures.', recommendedHours: null, language: 'fr', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-fr-cm1-food', documentId: 'minedub-fr-primary-3', sourcePdfPage: 93, sourcePrintedPage: 94, sourceLocator: 'Tableau 24, unité 1 la nature, alimentation, colonne CM1', level: 'CM1', subject: 'Sciences et technologies', domain: 'Sciences de la vie', officialUnit: 'Unité 1 : la nature', officialLesson: 'L’alimentation de l’homme', objectiveParaphrase: 'Classer les aliments selon leur rôle et expliquer pourquoi les besoins alimentaires varient.', competencyParaphrase: 'Relier alimentation, besoins humains et hygiène.', recommendedHours: null, language: 'fr', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-fr-cm2-food', documentId: 'minedub-fr-primary-3', sourcePdfPage: 93, sourcePrintedPage: 94, sourceLocator: 'Tableau 24, unité 1 la nature, alimentation, colonne CM2', level: 'CM2', subject: 'Sciences et technologies', domain: 'Sciences de la vie', officialUnit: 'Unité 1 : la nature', officialLesson: 'L’alimentation de l’homme', objectiveParaphrase: 'Composer une ration en tenant compte des besoins variables de la personne.', competencyParaphrase: 'Mobiliser les connaissances alimentaires et les règles d’hygiène.', recommendedHours: null, language: 'fr', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-en-class1-body', documentId: 'minedub-en-primary-1', sourcePdfPage: 51, sourcePrintedPage: 51, sourceLocator: 'Table 22, Health Education, Human body, Class 1 column', level: 'Class 1', subject: 'Science and Technology', domain: 'Health Education', officialUnit: 'Human body', officialLesson: null, objectiveParaphrase: 'Recognise different body parts and practise everyday cleanliness.', competencyParaphrase: 'Connect knowledge of the body with personal care.', recommendedHours: null, language: 'en', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-en-class2-body', documentId: 'minedub-en-primary-1', sourcePdfPage: 51, sourcePrintedPage: 51, sourceLocator: 'Table 22, Health Education, Human body, Class 2 column', level: 'Class 2', subject: 'Science and Technology', domain: 'Health Education', officialUnit: 'Human body', officialLesson: null, objectiveParaphrase: 'Connect body parts to what they do and choose appropriate items for cleaning them.', competencyParaphrase: 'Use knowledge of body functions in daily personal care.', recommendedHours: null, language: 'en', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-en-class3-bones', documentId: 'minedub-en-primary-2', sourcePdfPage: 52, sourcePrintedPage: 53, sourceLocator: 'Table 22, Health Education, The body, Class 3 column', level: 'Class 3', subject: 'Science and Technology', domain: 'Health Education', officialUnit: 'The body', officialLesson: null, objectiveParaphrase: 'Distinguish types of bones and value a clean appearance.', competencyParaphrase: 'Relate knowledge of the skeleton to personal care.', recommendedHours: null, language: 'en', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-en-class4-bones', documentId: 'minedub-en-primary-2', sourcePdfPage: 52, sourcePrintedPage: 53, sourceLocator: 'Table 22, Health Education, The body, Class 4 column', level: 'Class 4', subject: 'Science and Technology', domain: 'Health Education', officialUnit: 'The body', officialLesson: null, objectiveParaphrase: 'Explain the functions of body parts and ways of keeping bones strong.', competencyParaphrase: 'Apply knowledge of the body to healthy everyday practices.', recommendedHours: null, language: 'en', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-en-class5-systems', documentId: 'minedub-en-primary-3', sourcePdfPage: 53, sourcePrintedPage: 54, sourceLocator: 'Table 22, Health Education, Human body, Class 5 column', level: 'Class 5', subject: 'Science and Technology', domain: 'Health Education', officialUnit: 'Human body', officialLesson: null, objectiveParaphrase: 'Explain how body systems operate and represent them with labelled drawings.', competencyParaphrase: 'Use representations to explain the organisation of the human body.', recommendedHours: null, language: 'en', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
  { id: 'primary-en-class6-systems', documentId: 'minedub-en-primary-3', sourcePdfPage: 53, sourcePrintedPage: 54, sourceLocator: 'Table 22, Health Education, Human body, Class 6 column', level: 'Class 6', subject: 'Science and Technology', domain: 'Health Education', officialUnit: 'Human body', officialLesson: null, objectiveParaphrase: 'Describe the skeleton and explain its importance while practising habits that support healthy body systems.', competencyParaphrase: 'Connect body structure with everyday health practices.', recommendedHours: null, language: 'en', status: 'PEDAGOGICAL_APPROVAL_REQUIRED' },
];
