/** Short analytical paraphrases of four cached, hash-verified ministry guides.
 * Covers establish scope; indicated methodology pages were visually checked.
 * Local preparation outlines are original aids, not official blank forms. */
const frOutline = ['Classe et discipline', 'Unité / thème et référence', 'Situation à explorer', 'Objectif observable', 'Compétence travaillée', 'Prérequis vérifiés', 'Matériel et sécurité', 'Introduction', 'Actions de l’enseignant', 'Actions des apprenants', 'Exercice ou manipulation', 'Éléments essentiels à retenir', 'Vérification formative', 'Travail complémentaire si pertinent', 'Soutien et nouvelle preuve'];
const enOutline = ['Class and subject', 'Unit / topic and reference', 'Problem to investigate', 'Observable objective', 'Target competence', 'Checked prior knowledge', 'Materials and safety', 'Introduction', 'Teacher facilitation', 'Learner actions', 'Practice or investigation', 'Key learning points', 'Formative check', 'Optional extension', 'Support and new evidence'];
export const verifiedTeacherGuides: Record<string, { language: string; levels: string[]; subjects: string[]; locator: string; summary: string; outline: string[] }> = {
  '3': { language: 'en', levels: ['en-secondary-form1', 'en-secondary-form2'], subjects: ['Computer Science'], locator: 'PDF p.1 scope; p.6, §1.5 lesson preparation', summary: 'Plan around the topic, observable aims, available resources and learner needs. Arrange content and checks coherently; choose methods that let learners solve meaningful problems. Assessment criteria should relate to learning outcomes rather than comparison with classmates.', outline: enOutline },
  '7': { language: 'en', levels: ['en-secondary-form1', 'en-secondary-form2'], subjects: ['Mathematics'], locator: 'PDF p.1 Forms 1/2, August 2014; p.8 lesson preparation', summary: 'Use a realistic context consistent with the syllabus situation family. Check prior knowledge, organise discovery and practice, identify essential learning and review misunderstandings. The guide provides a preparation framework; this local outline does not assign official lesson times.', outline: enOutline },
  '30': { language: 'fr', levels: ['fr-secondary-6e', 'fr-secondary-5e'], subjects: ['Informatique'], locator: 'Couverture PDF p.1 ; §2.3 PDF p.7, page imprimée 6', summary: 'Définir le thème et les activités, confronter les supports pédagogiques, organiser un plan cohérent puis essayer le déroulement et préparer le matériel. Adapter la séance à l’environnement et l’actualiser après retour d’expérience. Le canevas local aide la préparation sans reproduire les fiches du guide.', outline: frOutline },
  '36': { language: 'fr', levels: ['fr-secondary-6e', 'fr-secondary-5e'], subjects: ['Sciences'], locator: 'Couverture PDF p.1, août 2014 ; PDF p.9, §IV-1', summary: 'Varier les activités actives, les échanges en petit groupe et la réflexion individuelle. Relier les connaissances à des situations concrètes adaptées aux apprenants et réserver un retour sur ce qui a été compris. La notice ne transpose aucune échelle de bulletin à ITALO.', outline: frOutline },
};
